name: "Deploy to lambda mailer"
on: 
  push:
    paths:
      - "apps/mailer/handler.js"
    branches:
      - 'master'
jobs:
  deploy_source:
    name: Deploy lambda from source file
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: generic-mail-handler
          source: apps/mailer/handler.js
