name: "Deploy to lambda mailer"
on: 
  push:
    paths:
      - "apps/mailer/*"
#    branches:
#      - 'master'
jobs:
  deploy_source:
    name: Deploy lambda from source file
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - run: yarn build
        working-directory: apps/mailer
      - name: default deploy
        uses: appleboy/lambda-action@master
        working-directory: apps/mailer
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: generic-mail-handler-v2
          source: dist/lambda.js
